import { useEffect, useState } from 'react';
import { CheckCircle2, RefreshCw, Search, ShieldCheck } from 'lucide-react';
import { adminCall } from './adminApi';

const prices = {
  business: { standard: 20000, referred: 19000 },
  premium: { standard: 35000, referred: 33000 },
};
const money = (amount) => `TSh ${Number(amount).toLocaleString('en-TZ')}`;

export default function AccessPanel({ reportError }) {
  const [email, setEmail] = useState('');
  const [user, setUser] = useState(undefined);
  const [plan, setPlan] = useState('business');
  const [grantKey, setGrantKey] = useState(() => crypto.randomUUID());
  const [confirmed, setConfirmed] = useState(false);
  const [busy, setBusy] = useState(false);
  const [grants, setGrants] = useState([]);
  const [result, setResult] = useState(null);
  const expectedAmount = prices[plan][user?.referred ? 'referred' : 'standard'];

  const loadHistory = async () => {
    try {
      const data = await adminCall('admin-general', { action: 'access_recent' });
      setGrants(data.grants || []);
    } catch (e) { reportError(e.message); }
  };
  useEffect(() => { loadHistory(); }, []);

  const lookup = async () => {
    reportError('');
    setResult(null);
    setBusy(true);
    try {
      const data = await adminCall('admin-general', { action: 'access_lookup', email: email.trim() });
      setUser(data.user || null);
    } catch (e) {
      setUser(undefined);
      reportError(e.message);
    } finally { setBusy(false); }
  };

  const grant = async () => {
    if (!user?.verified || !confirmed || busy) return;
    const price = money(expectedAmount);
    if (!window.confirm(`You verified receipt of ${price} for ${user.email}? Grant ${plan} access for 60 days?`)) return;
    reportError('');
    setBusy(true);
    try {
      const data = await adminCall('admin-general', {
        action: 'access_grant',
        email: user.email,
        plan,
        expected_amount: expectedAmount,
        grant_key: grantKey,
        // Compatibility with the previously deployed admin function. This is
        // generated by the app; the admin never enters a wallet reference.
        transfer_reference: `INTERNAL-${grantKey}`,
        confirmed: true,
      });
      setResult(data.grant);
      setGrantKey(crypto.randomUUID());
      setConfirmed(false);
      const refreshed = await adminCall('admin-general', { action: 'access_lookup', email: user.email });
      setUser(refreshed.user);
      await loadHistory();
    } catch (e) {
      reportError(/transfer reference has already been used/i.test(e.message)
        ? 'This access request was already recorded. Refresh recent grants before trying again.'
        : e.message);
    }
    finally { setBusy(false); }
  };

  return <>
    <section className="card compose">
      <div className="card-head"><h2>Manual payment access</h2>
        <p>Only for a payment you independently verified in your mobile-money account. The learner must first register and verify their email in the web app.</p>
      </div>
      <label>Learner's registered email
        <input type="email" value={email} onChange={(e) => { setEmail(e.target.value); setUser(undefined); setConfirmed(false); }} placeholder="student@example.com" />
      </label>
      <button type="button" className="secondary" disabled={busy || !email.trim()} onClick={lookup}><Search />{busy ? 'Checking…' : 'Find account'}</button>
      {user === null && <div className="alert error">No registered account has this email. Ask the learner to sign up first.</div>}
      {user && <div className="send-check">
        <strong>{user.full_name || 'Registered learner'} · {user.email}</strong>
        <p>{user.verified ? 'Email verified' : 'Email not verified — ask the learner to verify it first.'}
          {' '}Current plan: {user.plan || 'Free'}{user.expires_at ? ` (expires ${new Date(user.expires_at).toLocaleDateString()})` : ''}</p>
        {user.referred && <p>Referral code linked — use the referred price below.</p>}
      </div>}
      {user?.verified && <>
        <label>Access plan
          <select value={plan} onChange={(e) => { setPlan(e.target.value); setConfirmed(false); }}>
            <option value="business">Business — {money(prices.business[user?.referred ? 'referred' : 'standard'])}</option>
            <option value="premium">Premium — {money(prices.premium[user?.referred ? 'referred' : 'standard'])}</option>
          </select>
        </label>
        <label className="inline-check"><input type="checkbox" checked={confirmed} onChange={(e) => setConfirmed(e.target.checked)} />
          I checked my own wallet statement and received the full {money(expectedAmount)} for this learner.
        </label>
        <button type="button" className="primary" disabled={busy || !confirmed} onClick={grant}>
          <ShieldCheck />{busy ? 'Granting…' : `Grant ${plan} for 60 days`}
        </button>
      </>}
      {result && <div className="alert success"><CheckCircle2 />{result.email} has {result.plan} access {result.expires_at ? `until ${new Date(result.expires_at).toLocaleString()}` : 'for life'}.</div>}
    </section>
    <section className="card">
      <div className="card-head row"><div><h2>Recent manual grants</h2><p>Each grant is recorded automatically for your records.</p></div>
        <button type="button" className="icon-btn" aria-label="Refresh manual grants" onClick={loadHistory}><RefreshCw /></button>
      </div>
      {!grants.length && <div className="empty">No manual grants yet.</div>}
      {grants.map((item) => <div className="history-row" key={item.id}>
        <div><strong>{item.learner_email}</strong><small>{new Date(item.created_at).toLocaleString()}</small></div>
        <div className="counts"><strong>{item.plan}</strong><small>{money(item.amount)}</small></div>
      </div>)}
    </section>
  </>;
}
