import { useEffect, useState } from 'react';
import { ArrowDown, ArrowUp, Plus, Save, Trash2 } from 'lucide-react';
import { adminCall } from './adminApi';
import './assessments.css';

const question = () => ({ kind: 'mcq', question: '', options: ['', '', '', ''], correct_option_index: 0, model_answer: '', points: 1 });
const newExam = () => ({ title: '', description: '', instructions: '', pass_mark: 50, duration_minutes: 30, max_violations: 2, requires_project: false, certificate_enabled: true, is_published: false, papers: [1, 2, 3].map((version) => ({ version, questions: [question()] })) });
const newExercise = () => ({ title: '', description: '', instructions: '', pass_mark: 50, requires_assignment: true, is_published: false, questions: [question()] });

function Questions({ items, setItems }) {
  const set = (i, key, value) => setItems(items.map((x, n) => n === i ? { ...x, [key]: value } : x));
  const move = (i, delta) => { const next = [...items]; const target = i + delta; if (target < 0 || target >= next.length) return; [next[i], next[target]] = [next[target], next[i]]; setItems(next); };
  return <div>{items.map((x, i) => <div className="question-edit" key={i}><div className="row"><strong>Question {i + 1}</strong><button className="secondary" disabled={i === 0} onClick={() => move(i, -1)} title="Move up"><ArrowUp /></button><button className="secondary" disabled={i === items.length - 1} onClick={() => move(i, 1)} title="Move down"><ArrowDown /></button><button className="danger-link" onClick={() => setItems(items.filter((_, n) => n !== i))}><Trash2 /></button></div><select value={x.kind} onChange={(e) => set(i, 'kind', e.target.value)}><option value="mcq">Multiple choice</option><option value="short">Short answer</option></select><textarea placeholder="Question" value={x.question} onChange={(e) => set(i, 'question', e.target.value)} />{x.kind === 'mcq' ? x.options.map((option, oi) => <label className="option" key={oi}><input type="radio" checked={x.correct_option_index === oi} onChange={() => set(i, 'correct_option_index', oi)} /><input placeholder={`Option ${oi + 1}`} value={option} onChange={(e) => set(i, 'options', x.options.map((v, n) => n === oi ? e.target.value : v))} /></label>) : <textarea placeholder="Model answer" value={x.model_answer || ''} onChange={(e) => set(i, 'model_answer', e.target.value)} />}<label>Points<input type="number" min="1" value={x.points} onChange={(e) => set(i, 'points', Number(e.target.value))} /></label></div>)}<button className="secondary" onClick={() => setItems([...items, question()])}><Plus />Question</button></div>;
}

function Reviews({ items, kind, reload, reportError }) {
  const [note, setNote] = useState({});
  const [busy, setBusy] = useState('');
  const review = async (item, status) => {
    setBusy(item.id); reportError('');
    const message = note[item.id] || item.reviewer_note || (status === 'approved' ? `Your ${kind} was approved.` : `Your ${kind} needs changes. Please review the feedback in the app.`);
    try {
      await adminCall('admin-assessments', { action: 'review', kind, id: item.id, status, note: message });
      if (status !== 'pending') try { await adminCall('send-push-notification', { user_id: item.user_id, title: status === 'approved' ? `${kind === 'project' ? 'Project' : 'Assignment'} approved 🎉` : `${kind === 'project' ? 'Project' : 'Assignment'} needs changes`, message }); } catch (notificationError) { reportError(`Review saved, but learner notification failed: ${notificationError.message}`); }
      await reload();
    } catch (e) { reportError(e.message); } finally { setBusy(''); }
  };
  return <div>{items.length ? items.map((item) => <div className="review-card" key={item.id}><div><strong>{item.user_name}</strong><small>{new Date(item.created_at).toLocaleString()} · {item.status}</small><p>{item.note}</p>{(item.links || []).map((link, i) => <a key={i} href={link.url} target="_blank" rel="noreferrer">{link.kind}: {link.url}</a>)}</div><textarea placeholder="Reviewer note" value={note[item.id] ?? item.reviewer_note ?? ''} onChange={(e) => setNote({ ...note, [item.id]: e.target.value })} /><div className="row"><button className="approve" disabled={busy === item.id} onClick={() => review(item, 'approved')}>Approve & notify</button><button className="reject" disabled={busy === item.id} onClick={() => review(item, 'rejected')}>Reject & notify</button>{item.status !== 'pending' && <button className="secondary" disabled={busy === item.id} onClick={() => review(item, 'pending')}>Reopen</button>}</div></div>) : <div className="empty">No submissions waiting for review.</div>}</div>;
}

export default function AssessmentsPanel({ reportError }) {
  const [tab, setTab] = useState('exams');
  const [data, setData] = useState({ exams: [], exercises: [], projects: [], assignments: [] });
  const [edit, setEdit] = useState(null);
  const [busy, setBusy] = useState(false);
  const load = async () => { try { setData(await adminCall('admin-assessments', { action: 'list' })); } catch (e) { reportError(e.message); } };
  useEffect(() => { load(); }, []);
  const open = async (item) => { setBusy(true); try { const v = await adminCall('admin-assessments', { action: tab === 'exams' ? 'exam_detail' : 'exercise_detail', id: item.id }); setEdit(v[tab === 'exams' ? 'exam' : 'exercise']); } catch (e) { reportError(e.message); } finally { setBusy(false); } };
  const save = async () => { setBusy(true); reportError(''); try { await adminCall('admin-assessments', { action: tab === 'exams' ? 'save_exam' : 'save_exercise', [tab === 'exams' ? 'exam' : 'exercise']: edit }); setEdit(null); await load(); } catch (e) { reportError(e.message); } finally { setBusy(false); } };
  const remove = async (item) => { if (!confirm(`Delete “${item.title}” and its related content?`)) return; try { await adminCall('admin-assessments', { action: tab === 'exams' ? 'delete_exam' : 'delete_exercise', id: item.id }); await load(); } catch (e) { reportError(e.message); } };
  const togglePublished = async (item) => { setBusy(true); try { await adminCall('admin-assessments', { action: tab === 'exams' ? 'set_exam_published' : 'set_exercise_published', id: item.id, published: !item.is_published }); await load(); } catch (e) { reportError(e.message); } finally { setBusy(false); } };

  if (edit) {
    const set = (key, value) => setEdit({ ...edit, [key]: value });
    return <section className="card assessment-form"><div className="row"><h2>{edit.id ? 'Edit' : 'Create'} {tab === 'exams' ? 'exam' : 'exercise'}</h2><button className="secondary" onClick={() => setEdit(null)}>Close</button></div><label>Title<input value={edit.title} onChange={(e) => set('title', e.target.value)} /></label><label>Description<textarea value={edit.description || ''} onChange={(e) => set('description', e.target.value)} /></label><label>Instructions<textarea value={edit.instructions || ''} onChange={(e) => set('instructions', e.target.value)} /></label><div className="form-grid"><label>Pass mark<input type="number" min="1" max="100" value={edit.pass_mark} onChange={(e) => set('pass_mark', Number(e.target.value))} /></label>{tab === 'exams' && <><label>Duration minutes<input type="number" min="1" value={edit.duration_minutes} onChange={(e) => set('duration_minutes', Number(e.target.value))} /></label><label>Allowed violations<input type="number" min="0" value={edit.max_violations} onChange={(e) => set('max_violations', Number(e.target.value))} /></label></>}</div><div className="checks"><label><input type="checkbox" checked={edit.is_published} onChange={(e) => set('is_published', e.target.checked)} />Published</label><label><input type="checkbox" checked={tab === 'exams' ? edit.requires_project : edit.requires_assignment} onChange={(e) => set(tab === 'exams' ? 'requires_project' : 'requires_assignment', e.target.checked)} />Requires {tab === 'exams' ? 'project' : 'assignment'}</label>{tab === 'exams' && <label><input type="checkbox" checked={edit.certificate_enabled !== false} onChange={(e) => set('certificate_enabled', e.target.checked)} />Issue certificate after completion</label>}</div>{edit.locked && <div className="alert error">Learners have already attempted this item, so its questions are frozen. Metadata and publishing settings remain editable.</div>}{tab === 'exams' ? edit.papers.map((paper, pi) => <div className="paper" key={paper.id || pi}><h3>Paper {pi + 1}</h3><fieldset disabled={edit.locked}><Questions items={paper.questions} setItems={(questions) => set('papers', edit.papers.map((p, n) => n === pi ? { ...p, questions } : p))} /></fieldset></div>) : <fieldset disabled={edit.locked}><Questions items={edit.questions} setItems={(questions) => set('questions', questions)} /></fieldset>}<button className="primary" disabled={busy || !edit.title} onClick={save}><Save />{busy ? 'Saving…' : 'Save'}</button></section>;
  }

  return <><div className="subnav">{[['exams', 'Exams'], ['projects', 'Projects'], ['exercises', 'Quiz & Assignments'], ['assignments', 'Assignment reviews']].map(([key, label]) => <button className={tab === key ? 'active' : ''} onClick={() => setTab(key)} key={key}>{label}</button>)}</div>{(tab === 'projects' || tab === 'assignments') ? <section className="card"><h2>{tab === 'projects' ? 'Project' : 'Assignment'} reviews</h2><Reviews items={data[tab]} kind={tab === 'projects' ? 'project' : 'assignment'} reload={load} reportError={reportError} /></section> : <section className="card"><div className="card-head row"><div><h2>{tab === 'exams' ? 'Exams' : 'Exercises'}</h2><p>Author questions and control publishing.</p></div><button className="primary" onClick={() => setEdit(tab === 'exams' ? newExam() : newExercise())}><Plus />New</button></div>{data[tab].length ? data[tab].map((item) => <div className="catalog-row" key={item.id}><div><strong>{item.title}</strong><small>{item.is_published ? 'Published' : 'Draft'}{tab === 'exams' && item.certificate_enabled ? ' · certificate' : ''}</small></div><button className={item.is_published ? 'secondary published' : 'secondary'} disabled={busy} onClick={() => togglePublished(item)}>{item.is_published ? 'Unpublish' : 'Publish'}</button><button className="secondary" onClick={() => open(item)}>Edit</button><button className="danger-link" onClick={() => remove(item)}><Trash2 />Delete</button></div>) : <div className="empty">No items yet.</div>}</section>}</>;
}
