import { useEffect, useState } from 'react';
import { BookOpen, Plus, Save, Trash2, X } from 'lucide-react';
import { adminCall } from './adminApi';
import './course.css';

const blankQuestion = () => ({ question: '', options: ['', '', '', ''], correct_option_index: 0 });
const blankModule = () => ({ title: '', video_url: '', duration_seconds: 0, quiz: null });
const fileBase64 = (file) => new Promise((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result).split(',')[1]); reader.onerror = reject; reader.readAsDataURL(file); });
const blankCourse = () => ({ title: '', description: '', thumbnail_url: '', price: 0, duration_minutes: 0, authorship: 'ujuzi', is_published: false, certificate_enabled: false, access_tier: 'business', is_free: false, category_ids: [], announce: true, modules: [blankModule()] });

export default function CourseManager({ reportError, startNew = false, categoriesOnly = false }) {
  const [data, setData] = useState({ courses: [], categories: [] });
  const [editor, setEditor] = useState(startNew ? blankCourse() : null);
  const [busy, setBusy] = useState(false);
  const load = async () => { setBusy(true); try { setData(await adminCall('admin-dashboard', { action: 'courses' })); } catch (e) { reportError(e.message); } finally { setBusy(false); } };
  useEffect(() => { load(); }, []);
  const edit = async (id) => { setBusy(true); try { const value = await adminCall('admin-dashboard', { action: 'course_detail', course_id: id }); const course = value.course; setEditor({ ...course, access_tier: course.access_tier || (course.is_free ? 'free' : 'business') }); } catch (e) { reportError(e.message); } finally { setBusy(false); } };
  const change = (key, value) => setEditor((current) => ({ ...current, [key]: value }));
  const changeModule = (index, key, value) => change('modules', editor.modules.map((item, i) => i === index ? { ...item, [key]: value } : item));
  const changeQuiz = (mi, key, value) => changeModule(mi, 'quiz', { ...editor.modules[mi].quiz, [key]: value });
  const changeQuestion = (mi, qi, key, value) => changeQuiz(mi, 'questions', editor.modules[mi].quiz.questions.map((item, i) => i === qi ? { ...item, [key]: value } : item));
  const save = async () => {
    setBusy(true); reportError('');
    try {
      const course = { ...editor, is_free: editor.access_tier === 'free' };
      const isNew = !course.id;
      const announce = course.announce === true;
      delete course.announce;
      if (course._ebookFile) { const result = await adminCall('shop-upload', { type: 'course_ebook', filename: course._ebookFile.name, file_b64: await fileBase64(course._ebookFile) }); course.ebook_storage_key = result.key; }
      if (course._exerciseFile) { const result = await adminCall('shop-upload', { type: 'file', filename: course._exerciseFile.name, file_b64: await fileBase64(course._exerciseFile) }); course.exercise_pdf_storage_key = result.key; }
      delete course._ebookFile; delete course._exerciseFile;
      await adminCall('admin-dashboard', { action: 'save_course', course });
      if (isNew && course.is_published && announce) {
        try { await adminCall('send-push-notification', { title: `New course: ${course.title}`, message: `${course.title} is now available in Ujuzi Kidigitali.`, topic: 'all_users' }); }
        catch (notificationError) { reportError(`Course saved, but its announcement failed: ${notificationError.message}`); }
      }
      setEditor(startNew ? blankCourse() : null); await load();
    } catch (e) { reportError(e.message); } finally { setBusy(false); }
  };  const remove = async (course) => { if (!window.confirm(`Permanently delete “${course.title}” and its learning content?`)) return; setBusy(true); try { await adminCall('admin-dashboard', { action: 'delete_course', course_id: course.id }); await load(); } catch (e) { reportError(e.message); } finally { setBusy(false); } };
  const togglePublished = async (course) => { setBusy(true); reportError(''); try { const value = await adminCall('admin-dashboard', { action: 'set_course_published', course_id: course.id, published: !course.is_published }); setData((current) => ({ ...current, courses: current.courses.map((item) => item.id === course.id ? { ...item, ...value.course } : item) })); } catch (e) { reportError(e.message); } finally { setBusy(false); } };
  const saveCategory = async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); setBusy(true); try { await adminCall('admin-dashboard', { action: 'save_category', name: form.get('name'), slug: form.get('slug') }); event.currentTarget.reset(); await load(); } catch (e) { reportError(e.message); } finally { setBusy(false); } };
  const deleteCategory = async (id) => { if (!window.confirm('Delete this category and unlink it from courses?')) return; await adminCall('admin-dashboard', { action: 'delete_category', id }); await load(); };
  const editCategory = async (category) => { const name = window.prompt('Category name', category.name); if (!name) return; const slug = window.prompt('Category slug', category.slug); if (!slug) return; await adminCall('admin-dashboard', { action: 'save_category', id: category.id, name, slug }); await load(); };

  if (editor) return <section className="card editor"><div className="card-head row"><div><h2>{editor.id ? 'Edit course' : 'Create course'}</h2><p>Course details, categories, modules and quizzes.</p></div><button className="icon-btn" onClick={() => setEditor(null)}><X /></button></div>
    <div className="form-grid"><label>Course title<input value={editor.title} onChange={(e) => change('title', e.target.value)} /></label><label>Thumbnail URL<input value={editor.thumbnail_url || ''} onChange={(e) => change('thumbnail_url', e.target.value)} /></label><label className="wide">Description<textarea rows="4" value={editor.description} onChange={(e) => change('description', e.target.value)} /></label><label>Price (TZS)<input type="number" value={editor.price} onChange={(e) => change('price', e.target.value)} /></label><label>Duration (minutes)<input type="number" value={editor.duration_minutes} onChange={(e) => change('duration_minutes', e.target.value)} /></label><label>Prepared by<select value={editor.authorship} onChange={(e) => change('authorship', e.target.value)}><option value="ujuzi">Ujuzi Kidigitali</option><option value="supervised">Professional supervision</option></select></label></div><div className="form-grid"><label>Course e-book (PDF/EPUB)<input type="file" accept=".pdf,.epub" onChange={(e) => change('_ebookFile', e.target.files[0])} /></label><label>E-book title<input value={editor.ebook_title || ''} onChange={(e) => change('ebook_title', e.target.value)} /></label><label>Exercise PDF<input type="file" accept=".pdf" onChange={(e) => change('_exerciseFile', e.target.files[0])} /></label><label>Exercise PDF title<input value={editor.exercise_pdf_title || ''} onChange={(e) => change('exercise_pdf_title', e.target.value)} /></label></div>
    <div className="checks"><label><input type="checkbox" checked={editor.is_published} onChange={(e) => change('is_published', e.target.checked)} /> Published</label><label>Access package<select value={editor.access_tier || (editor.is_free ? 'free' : 'business')} onChange={(e) => change('access_tier', e.target.value)}><option value="free">Free</option><option value="business">Business</option><option value="premium">Premium</option></select></label><label><input type="checkbox" checked={editor.certificate_enabled} onChange={(e) => change('certificate_enabled', e.target.checked)} /> Certificate</label>{!editor.id && <label><input type="checkbox" checked={editor.announce !== false} onChange={(e) => change('announce', e.target.checked)} /> Announce published course to phones and in-app</label>}</div>
    <h3>Categories</h3><div className="chips">{data.categories.map((category) => <button key={category.id} className={editor.category_ids.includes(category.id) ? 'selected' : ''} onClick={() => change('category_ids', editor.category_ids.includes(category.id) ? editor.category_ids.filter((id) => id !== category.id) : [...editor.category_ids, category.id])}>{category.name}</button>)}</div>
    <h3>Modules and quizzes</h3>{editor.modules.map((module, mi) => <div className="module-edit" key={module.id || mi}><div className="row"><strong>Module {mi + 1}</strong><button className="danger-link" onClick={() => change('modules', editor.modules.filter((_, i) => i !== mi))}><Trash2 />Remove</button></div><div className="form-grid"><label>Title<input value={module.title} onChange={(e) => changeModule(mi, 'title', e.target.value)} /></label><label>Video URL / embed<input value={module.video_url || ''} onChange={(e) => changeModule(mi, 'video_url', e.target.value)} /></label><label>Duration (minutes)<input type="number" value={Math.round((module.duration_seconds || 0) / 60)} onChange={(e) => changeModule(mi, 'duration_seconds', Number(e.target.value) * 60)} /></label></div><button className="secondary" onClick={() => changeModule(mi, 'quiz', module.quiz ? null : { title: 'Mtihani', questions: [blankQuestion()] })}>{module.quiz ? 'Remove quiz' : 'Add quiz'}</button>{module.quiz && <div className="quiz-edit"><label>Quiz title<input value={module.quiz.title} onChange={(e) => changeQuiz(mi, 'title', e.target.value)} /></label>{module.quiz.questions.map((question, qi) => <div className="question-edit" key={qi}><div className="row"><strong>Question {qi + 1}</strong><button className="danger-link" onClick={() => changeQuiz(mi, 'questions', module.quiz.questions.filter((_, i) => i !== qi))}><Trash2 /></button></div><input placeholder="Question" value={question.question} onChange={(e) => changeQuestion(mi, qi, 'question', e.target.value)} />{question.options.map((option, oi) => <label className="option" key={oi}><input type="radio" name={`correct-${mi}-${qi}`} checked={question.correct_option_index === oi} onChange={() => changeQuestion(mi, qi, 'correct_option_index', oi)} /><input placeholder={`Option ${oi + 1}`} value={option} onChange={(e) => changeQuestion(mi, qi, 'options', question.options.map((item, i) => i === oi ? e.target.value : item))} /></label>)}</div>)}<button className="secondary" onClick={() => changeQuiz(mi, 'questions', [...module.quiz.questions, blankQuestion()])}><Plus />Question</button></div>}</div>)}
    <div className="editor-actions"><button className="secondary" onClick={() => change('modules', [...editor.modules, blankModule()])}><Plus />Module</button><button className="primary" disabled={busy} onClick={save}><Save />{busy ? 'Saving…' : 'Save course'}</button></div></section>;

  return <>{!categoriesOnly && <section className="card"><div className="card-head row"><div><h2>Courses</h2><p>Create and fully edit learning content.</p></div><button className="primary" onClick={() => setEditor(blankCourse())}><Plus />New course</button></div>{busy ? <div className="loading">Loading…</div> : <div className="course-list">{data.courses.map((course) => <div className="course-row" key={course.id}><div><strong>{course.title}</strong><small>{course.is_published ? 'Published' : 'Draft'} · {(course.access_tier || (course.is_free ? 'free' : 'business')).replace(/^./, (c) => c.toUpperCase())}</small></div><div className="row"><button className={course.is_published ? 'secondary publish-toggle published' : 'secondary publish-toggle'} disabled={busy} onClick={() => togglePublished(course)}>{course.is_published ? 'Unpublish' : 'Publish'}</button><button className="secondary" disabled={busy} onClick={() => edit(course.id)}>Edit</button><button className="danger-link" disabled={busy} onClick={() => remove(course)}><Trash2 /> Delete</button></div></div>)}</div>}</section>}{categoriesOnly && <section className="card"><div className="card-head"><h2>Categories</h2></div><form className="category-form" onSubmit={saveCategory}><input name="name" required placeholder="Category name" /><input name="slug" required placeholder="category-slug" /><button className="primary" disabled={busy}><Plus />Add</button></form><div className="chips category-list">{data.categories.map((category) => <span key={category.id}>{category.name}<button onClick={() => editCategory(category)}>Edit</button><button onClick={() => deleteCategory(category.id)}><Trash2 /></button></span>)}</div></section>}</>;;
}
