import { useEffect, useState } from 'react';
import { Plus, Trash2 } from 'lucide-react';
import { adminCall } from './adminApi';
import './meetings.css';

const session = () => ({ starts_at: '', time_label: '', duration_min: 60, duration_days: 0, capacity: 20, meeting_url: '' });
function currentSaturday() { const now = new Date(); const day = new Date(now.getFullYear(), now.getMonth(), now.getDate()); day.setDate(day.getDate() - ((day.getDay() + 1) % 7)); return day; }

export default function MeetingsPanel({ reportError }) {
  const [tab, setTab] = useState('meetings');
  const [data, setData] = useState({ slots: [], categories: [], courses: [], payouts: [] });
  const [form, setForm] = useState({ title: '', description: '', course_id: '', category_id: '', price_tsh: 20000, host_name: '', is_active: true, sessions: [session()] });
  const [category, setCategory] = useState('');
  const [busy, setBusy] = useState(false);
  const load = async () => { try { setData(await adminCall('admin-meetings', { action: 'list' })); } catch (e) { reportError(e.message); } };
  useEffect(() => { load(); }, []);
  const updateSession = (i, key, value) => setForm({ ...form, sessions: form.sessions.map((x, n) => n === i ? { ...x, [key]: value } : x) });
  const save = async () => { setBusy(true); reportError(''); try { await adminCall('admin-meetings', { action: 'save_slots', meeting: form }); setForm({ ...form, title: '', description: '', host_name: '', sessions: [session()] }); await load(); } catch (e) { reportError(e.message); } finally { setBusy(false); } };
  const remove = async (id) => { if (!confirm('Delete this meeting session?')) return; try { await adminCall('admin-meetings', { action: 'delete_slot', id }); await load(); } catch (e) { reportError(e.message); } };
  const addCategory = async () => { if (!category.trim()) return; try { await adminCall('admin-meetings', { action: 'save_category', name: category }); setCategory(''); await load(); } catch (e) { reportError(e.message); } };
  const deleteCategory = async (item) => { if (!confirm(`Delete filter “${item.name}”? Meetings using it will become unfiltered.`)) return; try { await adminCall('admin-meetings', { action: 'delete_category', id: item.id }); await load(); } catch (e) { reportError(e.message); } };
  const markPaid = async (payout) => { if (!confirm(`Confirm ${Number(payout.amount_tsh).toLocaleString()} TZS was paid for this week?`)) return; try { await adminCall('admin-meetings', { action: 'mark_paid', user_id: payout.user_id }); await load(); } catch (e) { reportError(e.message); } };

  return <><div className="subnav"><button className={tab === 'meetings' ? 'active' : ''} onClick={() => setTab('meetings')}>Meetings</button><button className={tab === 'payouts' ? 'active' : ''} onClick={() => setTab('payouts')}>Referral payouts</button></div>
    {tab === 'payouts' ? <section className="card"><h2>Pending referral payouts</h2><p className="hint">Current payout week: since Saturday {currentSaturday().toLocaleDateString()} at 00:00. The list resets each Saturday.</p>{data.payouts.length ? data.payouts.map((p) => <div className="payout-row" key={p.user_id}><div><strong>{p.profile?.full_name || 'User'}</strong><small>{p.profile?.phone || 'No phone — ask the user to add one'} · {p.reward_count} new this week · {p.total_invites} total invites</small></div><b>{Number(p.amount_tsh).toLocaleString()} TZS</b><button className="primary" onClick={() => markPaid(p)}>Mark paid</button></div>) : <div className="empty">No pending payouts this week.</div>}</section> : <>
      <section className="card meeting-form"><h2>Create meeting sessions</h2><div className="form-grid"><label>Title<input required value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /></label><label>Host<input value={form.host_name} onChange={(e) => setForm({ ...form, host_name: e.target.value })} /></label><label>Course<select value={form.course_id} onChange={(e) => setForm({ ...form, course_id: e.target.value })}><option value="">None</option>{data.courses.map((x) => <option value={x.id} key={x.id}>{x.title}</option>)}</select></label><label>Filter<select value={form.category_id} onChange={(e) => setForm({ ...form, category_id: e.target.value })}><option value="">None</option>{data.categories.map((x) => <option value={x.id} key={x.id}>{x.name}</option>)}</select></label><label>Price TZS<input type="number" min="0" value={form.price_tsh} onChange={(e) => setForm({ ...form, price_tsh: Number(e.target.value) })} /></label><label className="wide">Description<textarea value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></label><label className="inline-check"><input type="checkbox" checked={form.is_active} onChange={(e) => setForm({ ...form, is_active: e.target.checked })} />Active when published</label></div>
        {form.sessions.map((x, i) => <div className="session-row" key={i}><input type="datetime-local" title="Start date and time" value={x.starts_at} onChange={(e) => updateSession(i, 'starts_at', e.target.value)} /><input placeholder="Time label" value={x.time_label} onChange={(e) => updateSession(i, 'time_label', e.target.value)} /><input type="number" min="0" title="Minutes" placeholder="Minutes" value={x.duration_min} onChange={(e) => updateSession(i, 'duration_min', Number(e.target.value))} /><input type="number" min="0" title="Days" placeholder="Days" value={x.duration_days} onChange={(e) => updateSession(i, 'duration_days', Number(e.target.value))} /><input type="number" min="1" title="Capacity" placeholder="Capacity" value={x.capacity} onChange={(e) => updateSession(i, 'capacity', Number(e.target.value))} /><input placeholder="Meeting URL" value={x.meeting_url} onChange={(e) => updateSession(i, 'meeting_url', e.target.value)} /><button className="danger-link" disabled={form.sessions.length === 1} onClick={() => setForm({ ...form, sessions: form.sessions.filter((_, n) => n !== i) })}><Trash2 /></button></div>)}
        <div className="row"><button className="secondary" onClick={() => setForm({ ...form, sessions: [...form.sessions, session()] })}><Plus />Session</button><button className="primary" disabled={busy || !form.title || form.sessions.some((x) => !x.starts_at)} onClick={save}>{busy ? 'Publishing…' : 'Publish meeting'}</button></div></section>
      <section className="card"><h2>Meeting filters</h2><div className="row"><input value={category} onChange={(e) => setCategory(e.target.value)} placeholder="Filter name" /><button className="primary" disabled={!category.trim()} onClick={addCategory}>Add</button></div><div className="chips">{data.categories.map((x) => <span key={x.id}>{x.name}<button onClick={() => deleteCategory(x)}><Trash2 /></button></span>)}</div></section>
      <section className="card"><h2>All meeting sessions</h2>{data.slots.length ? data.slots.map((x) => <div className="catalog-row" key={x.id}><div><strong>{x.title}</strong><small>{new Date(x.starts_at).toLocaleString()} · {x.duration_days ? `${x.duration_days} day(s) · ` : ''}{x.duration_min} min · cap {x.capacity} · {x.is_active ? 'Active' : 'Hidden'}</small></div><button className="danger-link" onClick={() => remove(x.id)}><Trash2 />Delete</button></div>) : <div className="empty">No meeting sessions yet.</div>}</section>
    </>}
  </>;
}
